# Generated by Django 6.0.6 on 2026-06-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Escobar y.Cash', max_length=200, verbose_name='Nombre de la tienda')),
                ('slogan', models.CharField(blank=True, default='Calidad y tecnología para tu hogar', max_length=300, verbose_name='Eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('whatsapp', models.CharField(default='50575381352', max_length=50, verbose_name='Número WhatsApp')),
                ('whatsapp_message', models.TextField(default='Hola, me interesa este producto: {producto}. ¿Me podrían indicar el precio y disponibilidad?', verbose_name='Mensaje WhatsApp')),
                ('hero_titulo', models.CharField(blank=True, default='Los mejores electrodomésticos', max_length=200, verbose_name='Hero Título')),
                ('hero_subtitulo', models.TextField(blank=True, default='Calidad y tecnología para tu hogar', verbose_name='Hero Subtítulo')),
                ('direccion', models.CharField(blank=True, default='Av. Principal #123, Col. Centro', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='+505 7538-1352', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='contacto@escobarycash.com', max_length=254, verbose_name='Email')),
                ('horarios', models.CharField(blank=True, default='Lun - Sab: 9:00 - 20:00 | Dom: 10:00 - 18:00', max_length=200, verbose_name='Horarios')),
                ('facebook', models.URLField(blank=True, default='#', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='#', verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, default='#', verbose_name='Twitter (X)')),
                ('tiktok', models.URLField(blank=True, default='#', verbose_name='TikTok')),
                ('about_titulo', models.CharField(blank=True, default='Sobre Nosotros', max_length=200, verbose_name='About Título')),
                ('about_texto', models.TextField(blank=True, default='Somos una empresa dedicada a ofrecer los mejores electrodomésticos para tu hogar.', verbose_name='About Texto')),
                ('about_mision', models.TextField(blank=True, default='Ofrecer productos de calidad que mejoren la vida de nuestros clientes.', verbose_name='About Misión')),
                ('about_vision', models.TextField(blank=True, default='Ser la tienda de electrodomésticos líder en Nicaragua.', verbose_name='About Visión')),
                ('stats_anos', models.IntegerField(default=5, verbose_name='Años de experiencia')),
                ('stats_productos', models.IntegerField(default=500, verbose_name='Productos vendidos')),
                ('stats_clientes', models.IntegerField(default=1000, verbose_name='Clientes satisfechos')),
                ('stats_marcas', models.IntegerField(default=50, verbose_name='Marcas disponibles')),
                ('footer_credit', models.CharField(blank=True, default='© 2025 Escobar y.Cash. Todos los derechos reservados.', max_length=200, verbose_name='Créditos footer')),
                ('footer_descripcion', models.TextField(blank=True, default='Tu tienda de electrodomésticos de confianza.', verbose_name='Descripción footer')),
                ('meta_description', models.CharField(blank=True, default='Escobar y.Cash - Los mejores electrodomésticos para tu hogar', max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, default='electrodomésticos, hogar, Nicaragua', max_length=300, verbose_name='Meta Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
