# Generated by Django 6.0.6 on 2026-06-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='ESCOBAR Y. CASH', max_length=200, verbose_name='Nombre de la tienda')),
                ('slogan', models.CharField(blank=True, default='', max_length=300, verbose_name='Slogan')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del logo')),
                ('whatsapp', models.CharField(default='+50575381352', max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_message', models.TextField(default='Hola, me interesa este producto: [NOMBRE DEL PRODUCTO]. ¿Me podrían indicar el precio y disponibilidad?', verbose_name='Mensaje de WhatsApp')),
                ('hero_titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título del Hero')),
                ('hero_subtitulo', models.CharField(blank=True, default='', max_length=300, verbose_name='Subtítulo del Hero')),
                ('direccion', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('horarios', models.CharField(blank=True, default='', max_length=200, verbose_name='Horarios')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='Twitter / X')),
                ('tiktok', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('about_titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título About')),
                ('about_texto', models.TextField(blank=True, default='', verbose_name='Texto About')),
                ('about_mision', models.TextField(blank=True, default='', verbose_name='Misión')),
                ('about_vision', models.TextField(blank=True, default='', verbose_name='Visión')),
                ('stats_anos', models.IntegerField(default=0, verbose_name='Años de experiencia')),
                ('stats_productos', models.IntegerField(default=0, verbose_name='Productos disponibles')),
                ('stats_clientes', models.IntegerField(default=0, verbose_name='Clientes satisfechos')),
                ('stats_marcas', models.IntegerField(default=0, verbose_name='Marcas')),
                ('footer_credit', models.CharField(blank=True, default='', max_length=200, verbose_name='Créditos del footer')),
                ('footer_descripcion', models.TextField(blank=True, default='', verbose_name='Descripción del footer')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
