# Generated by Django 6.0.6 on 2026-06-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='banners/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['sort_order'],
            },
        ),
    ]
